#!/bin/sh

[ $# -lt 1 ] && echo "Usage; ${0} <apk>" && exit 1

pkg=$(aapt dump badging $1 | awk -F" " '/package/ {print $2}' | awk -F"'" '/name=/ {print $2}')
activity=$(aapt dump badging $1 | awk -F" " '/launchable-activity/ {print $2}' | awk -F"'" '/name=/ {print $2}')
adb shell am start -n ${pkg}/${activity}
